// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czwkrupnyvfwmkrvkmel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6d2tydXBueXZmd21rcnZrbWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTU1MDIsImV4cCI6MjA2OTQzMTUwMn0.3ea6Yb93wR9QXDGh9cpeM1-jgw17dKm6-My27Kd6J1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});